# -*- coding: utf-8 -*-
"""AED.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bg__jErScU-ejlkQK8p8Af7i3tIqGZCj
"""

#Importação das bibliotecas de uso na análise.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import zipfile
import os

os.environ['KAGGLE_USERNAME'] = 'guilhermebstella'
os.environ['KAGGLE_KEY'] = '710d19fdcfada37e89085fc6dfdb5c52'

!pip install kaggle;
!kaggle datasets download -d nalisha/heart-disease-prediction-dataset;
with zipfile.ZipFile("heart-disease-prediction-dataset.zip", "r") as z:
    z.extractall();

df = pd.read_csv('Heart_Disease_Prediction.csv')
df.shape

df.info()

df.head()

df.describe()

df.duplicated()

x = df['Cholesterol']
y = df['Age']

fig, ax = plt.subplots(figsize=(8, 8))

sns.scatterplot(x=x, y=y, s=6, color="black", alpha=0.8, ax=ax)
sns.histplot(x=x, y=y, bins=60, pthresh=0.05, cmap="rocket", cbar=True, ax=ax)
sns.kdeplot(x=x, y=y, levels=8, color="blue", linewidths=1.2, ax=ax)

ax.set_title("Age vs Cholesterol Distribution")

plt.show()

sns.boxplot(x='Heart Disease', y='Age', data=df)
plt.show()

bp_age = df[['Cholesterol','BP']].copy()
bp_age['Cholesterol_bins'] = pd.cut(bp_age['Cholesterol'], bins=5, labels=False)
sns.violinplot(x='Cholesterol_bins', y='BP', data=bp_age)
plt.title('Distribution of BP across Cholesterol Bins')
plt.show()

coluns = ['Age', 'BP', 'Cholesterol','Max HR', 'ST depression', 'Slope of ST', 'Chest pain type','Thallium','Heart Disease']
fig, axs = plt.subplots(3, 3, figsize=(15, 10))

for ax, col in zip(axs.flat, coluns):
    sns.histplot(df[col], ax=ax)

plt.tight_layout()
plt.show()

sns.lineplot(y='Cholesterol', x='FBS over 120', estimator='mean',data=df)
plt.title('Cholesterol vs FBS over 120')
plt.xlabel('Cholesterol')
plt.ylabel('FBS over 120')
plt.show()

sns.lineplot(x='Age', y='BP', estimator='mean',data=df)
plt.title('Age vs BP')
plt.xlabel('Age')
plt.ylabel('BP')
plt.show()

numeric_data = df.select_dtypes(include='number')

corr = numeric_data.corr()

plt.figure(figsize=(15,15))
sns.heatmap(data=corr, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title("Correlation Heatmap")
plt.show()

